### ISSUE TITLE
Make sign in button on navbar appear only on non-landing page

### ISSUE THREAD

**Issue by hellodommy** [degreely/degreely#8]
<img width="512" alt="Screenshot 2020-10-25 at 3 24 59 PM" src="https://user-images.githubusercontent.com/47271661/97101192-3f8dc480-16d6-11eb-897d-7e0dda671e8a.png">

Want `Sign in to SSO` button on the navbar to appear only on the About and Support page (landing page doesn't need because there's already one on the page itself), but unable to pass props to `LandingHeader` to do so because the same `LandingHeader` is used in `App.js` for all route paths.

```
    <Router basename="/degreely">
      <LandingHeader />
      <Switch>
        <Route path="/about" component={AboutPage} />
        <Route path="/support" component={SupportPage} />
        <Route path="/settings" component={SettingsPage} />
        <Route path="/" component={LandingPage} />
      </Switch>
    </Router>
```

**Comment by flxffy** [comment]
You can check current path in `LandingHeader` and render the button conditionally. Probably could refer to [this](https://reactrouter.com/web/api/Hooks/uselocation)
